source 'git@code.amh-group.com:iOSYmm/mb-specrepo.git'
source 'git@code.amh-group.com:cocoapods/mb-thirdpartyspecrepo.git'  # 满帮内网第三方库
#use_frameworks!
use_modular_headers!
platform :ios, '10.0'

target 'MBRouterDebug_Example' do
  pod 'MBRouterDebug', :path => '../'
  pod 'MBStorageLib'
#  pod 'MBDoctor'

  target 'MBRouterDebug_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings["DEVELOPMENT_TEAM"] = "LJTDBM4U3C"
    end
  end
end
