source 'git@code.amh-group.com:iOSYmm/mb-specrepo.git'
source 'git@code.amh-group.com:cocoapods/mb-thirdpartyspecrepo.git'  # 满帮内网第三方库
source 'git@code.amh-group.com:iOSYmm/mb-binary-specrepo.git'

use_modular_headers!

platform :ios, '10.0'

target 'MBBridgeLibDebug_Example' do
  pod 'MBBridgeLibDebug', :path => '../'

  target 'MBBridgeLibDebug_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
