source "git@code.amh-group.com:cocoapods/mb-thirdpartyspecrepo.git"  # 满帮内网第三方库
source "git@code.amh-group.com:iOSYmm/mb-specrepo.git"

#use_frameworks!
use_modular_headers!

platform :ios, "11.0"

target "MBAPMLib_Example" do
  # pod 'Reachability', '~> 3.5.0'
  pod "MBAPMLib", :path => "../"
  pod 'MBAPMServiceLib', :path => '../'
  pod 'MBAPMDebug', :path => '../'
  pod 'Matrix', :path => '../../matrix-wechat/'
  target "MBAPMLib_Tests" do
    inherit! :search_paths

    pod "Kiwi"
  end
end

def mb_pod_post_install()
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["HEADER_SEARCH_PATHS"] = ["$(inherited)", "$(BUILT_PRODUCTS_DIR)/$(CONTENTS_FOLDER_PATH)/Headers"]
        config.build_settings["ENABLE_BITCODE"] = "NO"
        config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "11.0"
        #                config.build_settings['GCC_PRECOMPILE_PREFIX_HEADER'] = 'NO'
        # Debug 下不不编译dsym，用于减少运行时的 warning
        config.build_settings["DEBUG_INFORMATION_FORMAT"] = "dwarf"
        config.build_settings["DEVELOPMENT_TEAM"] = "33NTY77JS5"
        #                config.build_settings['CLANG_ENABLE_MODULES'] = 'NO'
        #                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = ['$(inherited)', 'DEBUG=1']
      end
    end
  end
end

mb_pod_post_install()

`git update-index --assume-unchanged ../MBAPMLib/Classes/Tools/Utils/DeviceInfo/MBDeviceInfo.mm`
`git update-index --assume-unchanged MBAPMLib/Classes/Tools/Utils/DeviceInfo/MBDeviceInfo.mm`

