source 'git@code.amh-group.com:iOSYmm/mb-specrepo.git'
source 'git@code.amh-group.com:cocoapods/mb-thirdpartyspecrepo.git'  # 满帮内网第三方库


# Uncomment the next line to define a global platform for your project
#use_frameworks!
use_modular_headers!
platform :ios, '10.0'

target 'MBDebug' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MBDebug
  pod 'MBDebug', :path=>'../'
end
