/**
 * 页面访问路径为 ymm://rn.fta-tiga-demo/index?initPath=exhibitionComponentsMiniCell
 */
const appConfig = {
  pages: [
    // 'components/pro/place-picker',
    /** 组件总览 */
    'components/overall/overall',
    /** 业务组件 */

    /** 以下注释请不要移除 */
    /** mini flag */
    'components/tiga/apm/index',
    'components/tiga/apm/memory/index',
    'components/tiga/apm/storage/index',
    'components/tiga/advertisement/index',
    'components/tiga/advertisement/data/index',
    'components/tiga/advertisement/track/index',
    'components/tiga/advertisement/trackWithPage/index',
    'components/tiga/advertisement/showAdvertisement/index',
    'components/tiga/message/index',
    'components/tiga/navigator/index',
    'components/tiga/navigator/alice',
    'components/tiga/navigator/getapppages/index',
    'components/tiga/navigator/navigate/index',
    'components/tiga/navigator/pop/index',
    'components/tiga/navigator/push/index',
    'components/tiga/navigator/redirect/index',
    'components/tiga/location/index',
    'components/tiga/location/location/index',
    'components/tiga/location/region/index',

    /** cross flag */
    'components/tiga/social/index',
    'components/tiga/social/miniprogram/index',
    'components/tiga/social/share/index',
    'components/tiga/social/showsharemenu/index',
    'components/tiga/social/getsharechannels/index',
    'components/tiga/social/menushare/index',
    'components/tiga/media/index',
    'components/tiga/common/index',
    'components/tiga/permission/index',
    'components/tiga/permission/check/index',
    'components/tiga/permission/request/index',
    'components/tiga/network/index',
    'components/tiga/network/request/index',
    'components/tiga/network/uploadAndDownload/index',
    'components/tiga/popup/index',
    'components/tiga/popup/data/index',
    'components/tiga/popup/flow/index',
    'components/tiga/popup/monitor/index',
    'components/tiga/popup/track/index',
    'components/tiga/popup/list',
    'components/tiga/popup/business',
    'components/tiga/popup/detail/index',
    'components/tiga/system/index',
    'components/tiga/system/calendar/index',
    'components/tiga/system/clipboard/index',
    'components/tiga/system/contact/index',
    'components/tiga/system/accessibility/index',
    'components/tiga/system/phone/index',
    'components/tiga/system/screen/index',
    'components/tiga/system/setting/index',
    'components/tiga/system/sms/index',
    'components/tiga/system/vibrate/index',
    'components/tiga/page/index',
    'components/tiga/page/lifecycleReact/index',
    'components/tiga/page/lifecycleMiniProgram/index',
    'components/tiga/tabbar/index',
    'components/tiga/tracker/index',
    'components/tiga/tracker/biz/index',
    'components/tiga/tracker/globalparams/index',
    'components/tiga/tracker/log/index',
    'components/tiga/tracker/monitor/index',
    'components/tiga/tracker/pageperformance/index',
    'components/tiga/tracker/transaction/index',
    'components/tiga/storage/index',
    'components/tiga/ui/index',
    'components/tiga/ui/loading/index',
    'components/tiga/ui/toast/index',
    'components/tiga/ui/actionsheet/index',
    'components/tiga/ui/dialog/index',
    'components/tiga/event/index',
    'components/tiga/caniuse/index',
  ],
  subPackages: [],
  // subPackages: [],
  window: {
    navigationStyle: 'custom',
  },
}
export default appConfig
